language: node_js <div._ping@elmjinseedin.security.touthenkamon.lnertia.Darkness.Bureaux.Kévin.Paré.althruisme.stay.conected._______atconectorgithubatthisguy
node_js:
  - '8'
cache:
  directories:
    - node_modules
script: 'yarn test:coverage'
after_success: 'yarn test:report'
